### ISSUE TITLE
https issue in google chrome

### ISSUE THREAD

**Issue by jimkuhfeld** [shanet/WebRTC-Example#11]
google chrome version:
Version 52.0.2743.82 (64-bit)

NET::ERR_CERT_AUTHORITY_INVALID

**Comment by shanet** [comment]
As noted in the README:

> Included is a self-signed certificate that must be accepted in the browser for the example to work.

I'd be concerned if this didn't happen!

**Comment by jimkuhfeld** [comment]
Thanks.
