### ISSUE TITLE
Unable to get streams from if client and server are on a different network

### ISSUE THREAD

**Issue by danishnazir** [shanet/WebRTC-Example#12]
Hello there i was unable to show the streams between different clients and server when they were on a different network!.

**Comment by shanet** [comment]
Hi Danish, there's no reason for this not to work from two independent boxes. However, "it doesn't work" isn't enough info for me to make any useful suggestions let alone reproduce the issue. It's worth noting that WebRTC uses ports than the usual 80 & 443. Are you sure that there's not a firewall or something sitting in between the two computers? If you're trying to make a connection over the open internet and don't have port forwarding configured on your router/gateway then you'll need to set up a TURN server.

**Comment by danishnazir** [comment]
Thanks gor the help sir actually i want this to work without port
forwarding and now you have told me that for that we have to use turn
server i will do that do you have any sample in which we can use both the
servers? Thanks

**Comment by shanet** [comment]
No, I don't have an example using a TURN server anywhere. It's relatively straightforward though and well documented in the WebRTC documentation. Here's an open source implementation you can host yourself: https://github.com/coturn/coturn.

**Comment by danishnazir** [comment]
Thanks alot Sir
