### ISSUE TITLE
How to change pair?

### ISSUE THREAD

**Issue by luisdemarchi** [shanet/WebRTC-Example#15]
First of all I'm sorry for my English, I'm Brazilian. Your code works very well, but in a test with 6 computers, when you click the "Start" button a second time, it will no longer work. What I wanted was to switch to another pair. Can you help?

**Comment by shanet** [comment]
This example is designed for a direct connection between two clients only. A non-trivial amount of work is required for multi-client calls. It's possible to connect an arbitrary number of clients at once, but quickly becomes impractical beyond three or so without using something like Jitsi Videobridge.

**Comment by luisdemarchi** [comment]
I want to make only two client connections at a time, but I need the "start" button to always search for a new connection (disconnecting the previous one). When I press "start" for the second time on, no one appears or a black screen appears and only the audio works.

**Comment by shanet** [comment]
It should just be a matter of resetting the state then. That is, close the existing peer connection and allow a new one to be started.

**Comment by Globik** [comment]
Is this demo for one tab? Or can one use it in two tabs at a time?

**Comment by Globik** [comment]
On the same computer from ff to chrome and vice versa does'nt work. Tested.

**Comment by Globik** [comment]
What for then negotiation needed event? Occurs in chrome, but not in a ff.

**Comment by shanet** [comment]
Calling Chrome to Firefox works for me currently with versions 57 and 53 respectively.

And yes, two browser tabs/windows or computers are needed so they have something to connect to. A single browser tab on its own won't do anything.

**Comment by Globik** [comment]
Yes, I see. Two tabs. Deployd to heroku, one need a turn server url when from different computers. When from tab to tab on the same computer and the same network is ok without turn url.
