### ISSUE TITLE
ws broadcast

### ISSUE THREAD

**Issue by renambot-uic** [shanet/WebRTC-Example#16]
To make it work, I had to update the broadcast from WS:

// Broadcast to all. 
wss.broadcast = function broadcast(data) {
  wss.clients.forEach(function each(client) {
    if (client.readyState === WebSocket.OPEN) {
      client.send(data);
    }
  });
};

**Comment by bfishman** [comment]
Hah!  Wish I had checked the issues, I just spent 45 minutes tracing this. Came here to report on my findings, which you already did :)

Anyway, I can at least confirm that I also had to do so. Running Node v7.6.0...

**Comment by shanet** [comment]
Thanks for the reports everyone. I'll get this fixed.

**Comment by bfishman** [comment]
Thank you for this example @shanet !  It was instrumental to have this "bare bones" wrtc example to quickly fall back to when troubleshooting an issue with my reverse proxy.
