### ISSUE TITLE
WebSocket / WebRTC

### ISSUE THREAD

**Issue by Gaspadlo** [shanet/WebRTC-Example#18]
I found this on your blog, there was no comment section.

Aren't Websockets and WebRTC two different things? You call it and name it WebRTC while using WebSockets.

WebRTC - high-performance over UDP
WebSocket - bidirectional over TCP.

https://stackoverflow.com/questions/18799364/webrtc-vs-websockets-if-webrtc-can-do-video-audio-and-data-why-do-i-need-web

**Comment by shanet** [comment]
Yes, that's correct. Websockets are client-to-server while webrtc is client-to-client (or client-to-server if using a TURN server).

**Comment by Gaspadlo** [comment]
I am not a networking expert, but client x client / client x server seems irrelevant to me. If i understand correctly the nature of communication the main difference of TCP & UDP:
UDP - does not expect response, lost packets aren't resent
results in lower com. delays, suitable for live streams, high tick-rate game communication, definitely not suitable for integrity sensitive data (for example online game movement is suitable to be communicated via UDP | login to hive server, items transactions via TCP)
TCP - generally commoner, expects response, a bit higher com. delay, lost packets are resent

Therefore I believe WebRTC and WebSockets are suitable for different cases.

**Comment by shanet** [comment]
The difference between the two is more than just TCP vs UDP. They're different protocols designed for different use cases.
