### ISSUE TITLE
only works locally?

### ISSUE THREAD

**Issue by nova76** [shanet/WebRTC-Example#2]
I tried to use a remote server, but it is not working. The remote video does not appear, only a black screen . The scripts were changed only the WebSocket server path. Any ideas ?

**Comment by shanet** [comment]
Works for me on my LAN. Are the necessary ports open? The server uses 3434, but WebRTC uses other ports.

**Comment by nova76** [comment]
I thought wrong. It does not have a problem with the remote server , but the error occurs when two clients on different machines I wanted to put together . The connection works two different browsers , even if they are on the same machine. Some error messages:

Kliens A chrome console:
webrtc.js:67 got description
webrtc.js:79 Failed to set remote offer sdp: Called in wrong state: STATE_SENTINITIATE
webrtc.js:74 got remote stream
webrtc.js:79 CreateAnswer failed because remote_description is not an offer.

Kliens B chrome console:
webrtc.js:74 got remote stream
webrtc.js:67 got description
webrtc.js:79 Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS

**Comment by shanet** [comment]
Chrome version and OS?

**Comment by nova76** [comment]
Chrome: 46.0.2490.86 m
Windows 8.1

Firewall not be the problem . WebRTC works in other places. For example 
https://appear.in/ 
https://apprtc.appspot.com/ .
But those places do not have such a beautiful and comprehensible description, as here :-)

**Comment by shanet** [comment]
I'm unable to reproduce this. I tested it on Windows 8 and with Chrome 46. And since I rarely use Windows, I had the node server running on a remote Linux box and the client files served with Python's SimpleHTTPServer. The only modification was changing the `127.0.0.1` in the `webrtc.js` file. I do see the same console output as you reported, but it still works fine with that output.

**Comment by nova76** [comment]
And two separate client machine or one machine with two browser windows ? The latter works here, too. But the relationship has not been established in two separate machine, only a black screen displayed. 
A total of three machine you tried ? One server and two clients, who are communicating with each other?

thanks for reply

**Comment by shanet** [comment]
Tried it again, this time with the server running on a Linux box, client 1 as Firefox on OSX, and client 2 as Chrome on Windows. All machines on the same LAN with no firewalls between them. Still unable to reproduce any problems.
