### ISSUE TITLE
URL.createObjectURL(stream) is deprecated, please use elem.srcObject = stream instead

### ISSUE THREAD

**Issue by JoseGoncalves** [shanet/WebRTC-Example#20]
With latest Chrome (v62) I am getting this warning.
The warning is self-explanatory of what needs to be done, i.e., replace, _localVideo.src = window.URL.createObjectURL(stream);_ with _localVideo.srcObject = stream;_ and _remoteVideo.src = window.URL.createObjectURL(event.stream);_ with _remoteVideo.srcObject = event.stream;_.

**Comment by pomle** [comment]
PR for this in https://github.com/shanet/WebRTC-Example/pull/24

Fixes it for Safari.

**Comment by shanet** [comment]
I just merged the patch fixing this. Thanks guys.
