### ISSUE TITLE
stun.services.mozilla.com requires authentication

### ISSUE THREAD

**Issue by JoseGoncalves** [shanet/WebRTC-Example#27]
You should remove _stun.services.mozilla.com_ from the list of STUN servers to use, as this currently requires authentication (see Example at [MDN RTCConfiguration](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration)). I would suggest to replace it with _stun.stunprotocol.org_.

**Comment by shanet** [comment]
Updated. Thanks!
