### ISSUE TITLE
Question on deploying on ios app

### ISSUE THREAD

**Issue by fsp-rts-2** [shanet/WebRTC-Example#29]
Hi, may I ask how to implement your webrtc example in an ios app?

**Comment by shanet** [comment]
This example was written for Firefox and Chrome's implementations of WebRTC. For iOS you'd need to rely on what Safari provides or some other third party library. Beyond that, I don't know. I haven't worked with iOS in many years now.

**Comment by prashant343** [comment]
its not working on iOS chrome client not even Safari

**Comment by ghost** [comment]
@prashant343  Try updating your HTML video elements to include 'playsinline'

    <video id="localVideo" autoplay playsinline muted></video>
    <video id="remoteVideo" autoplay playsinline></video>

**Comment by prashant343** [comment]
Sure will try and update

**Comment by easingthemes** [comment]
`playsinline` fixed Safari on iOS issue.

**Comment by prashant343** [comment]
yes working on iOS thanks

**Comment by shanet** [comment]
Thanks all, I added `playsinline` to the example code here.
