### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zibri** [shanet/WebRTC-Example#30]
got description
VM36 webrtc.js:92 DOMException: Failed to set remote offer sdp: Called in wrong state: kHaveLocalOffer
6VM36 webrtc.js:92 DOMException: Error processing ICE candidate

**Comment by giandrea77** [comment]
I think this error happening when you are calling from same IP

**Comment by shanet** [comment]
Hi @Zibri, I'm catching up on issues in this repo. Noted your error. Without steps to reproduce it or more info there's not I can do here, however.
