### ISSUE TITLE
I can not see the remote interlocutor

### ISSUE THREAD

**Issue by mikl43** [shanet/WebRTC-Example#33]
Hello, I can not see the remote interlocutor. I did it like in the code, everything works fine and when you press the button, the start of the video connection two times receives the video stream from the remote interlocutor, but there is no video. The signaling server is built on the WebSocket java library, data through this server is perfectly sent to two interlocutors. I also use https on the signaling server, it receives and sends connection data and formats perfectly, and the interlocutors accept this data and the function of receiving the remote video signal is triggered, but the video does not.

**Comment by mikl43** [comment]
I check on two computers, one computer in Russia and another computer (laptop) in the USA.

**Comment by mikl43** [comment]
All good!!!!! Need add turn servers!!!

**Comment by eightlines** [comment]
What was the change that you made?

**Comment by mikl43** [comment]
I add turn server for mobile internet.

чт, 20 дек. 2018 г. в 16:19, Brent Marshall <notifications@github.com>:

**Comment by shanet** [comment]
Closing as this seems to be resolved.
