### ISSUE TITLE
Invalid peerConnectionConfig

### ISSUE THREAD

**Issue by Andromelus** [shanet/WebRTC-Example#34]
Hi.

I just tried your code, curious about this tech, and there is a little problem:

In webrtc.js, the following variable is not correct (taken from the source repo):

```
var peerConnectionConfig = {
  'iceServers': [
    {'urls': 'stun:stun.stunprotocol.org:3478'},
    {'urls': 'stun:stun.l.google.com:19302'},
  ]
};
```

The error is the following:

> SyntaxError: RTCPeerConnection constructor passed invalid RTCConfiguration - improper scheme: stun1.l.google.com webrtc.js:42:20 

However, using the variable your provide at https://shanetully.com/2014/09/a-dead-simple-webrtc-example/ fixes the error.

`var peerConnectionConfig = {'iceServers': [{'url': 'stun:stun.services.mozilla.com'}, {'url': 'stun:stun.l.google.com:19302'}]};`

**Comment by shanet** [comment]
Hi @Andromelus, I'm catching up on issues in this repo. As far as I know, `stun:stun.l.google.com:19302` is a valid hostname (it resolves correctly for me locally). This is a few years old now so it may be fixed, but I suspect it was an issue with a specific browser that caused the problem with it.
