### ISSUE TITLE
Is it possible to add sample code to support node-webrtc

### ISSUE THREAD

**Issue by manhingcctil** [shanet/WebRTC-Example#36]
Hi,

I am new to webrtc, and I would like to implement peer-to-server for audio and video. I use existing code as client & signal server, and use "node-webrtc" as "peer-to-server"'s server, it can build up the connection, but the server side cannot receive video stream. Attached file is my test code by node-webrtc.

[index.zip](https://github.com/shanet/WebRTC-Example/files/4076374/index.zip)

**Comment by shanet** [comment]
Hi @manhingcctil, I'm catching up on issues in this repo. I'm not sure about node-webrtc, but it's outside the scope of this example regardless.
