### ISSUE TITLE
Connection is usually dropped whenever I tried to share screen.

### ISSUE THREAD

**Issue by web-sudo** [shanet/WebRTC-Example#38]
`https://github.com/web-sudo/webrtc` it's working well on localhost, meaning between 2 tabs on my local.
With livesite it works well between 2 tabs on local.
But in case 2 users would try to join and then when one of them tries to share each one's desktop screen the connection is usually dropped.

Can you plz check what the reason is?

**Comment by shanet** [comment]
Hi @web-sudo, I'm catching on issues on this project. I don't know why it would drop when sharing your screen. It's potentially something specific to your operating system and outside the scope of this example.
