### ISSUE TITLE
Always display "waiting for (IP)", works, then displays error as given in the comments

### ISSUE THREAD

**Issue by pranjalisnow** [shanet/WebRTC-Example#39]
While running on browser, it keeps displaying "waiting for <server IP>".

After closing both the the browsers, command window displays an error.
This is the error at the end...

      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on WebSocket instance at:
    at WebSocket.finalize (C:\inetpub\pkVC1\node_modules\ws\lib\WebSocket.js:182:41)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WebRTC-Example@1.0.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WebRTC-Example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-08-08T09_45_25_858Z-debug.log

**Comment by shanet** [comment]
Hi @pranjalisnow, I'm catching up on issues in this repo. I'm not sure where this is coming from, it looks like maybe something with the WS library running on Windows. I never intended for this to be run on Windows and am honestly not really interested in supporting Windows. If you can replicate it on a Unix-like system please let me know.
