### ISSUE TITLE
Cannot connect 2 different users from 2 different networks. 

### ISSUE THREAD

**Issue by vol-and** [shanet/WebRTC-Example#41]
First of all - thank you for your solution on multiple user videochat. I was studying over other examples, but ended up here, because it is open source and simple (but not much for me, as I am a begginer) to use. I would be very grateful if you could guide me quick through some points.

The thing is: I deployed your code on a Plesk server with the following changes:

**server.js**
```
const HTTPS_PORT = 8443; //default port for https is 443
const HTTP_PORT = 8443; //default port for http is 80

```
_and changed paths to files_

```
 if (request.url === '/webrtc.js') {
    response.writeHead(200, { 'Content-Type': 'application/javascript' });
    response.end(fs.readFileSync('public/webrtc.js'));
  } else if (request.url === '/style.css') {
    response.writeHead(200, { 'Content-Type': 'text/css' });
    response.end(fs.readFileSync('public/style.css'));
  } else {
    response.writeHead(200, { 'Content-Type': 'text/html' });
    response.end(fs.readFileSync('public/index.html'));
  }
};
```

**webrtc.js**
```
      .then(() => {
        serverConnection = new WebSocket('wss://' + 'localhost' + ':' + WS_PORT + '/');
```
Node.js: 
Document root:  /httpdocs/public
Application URL:  http://someurl.dev
Application root:  /httpdocs

So the structure on the server is:
```
**httpdocs/**
    |__ server.js
    |__ package.json
    |__ package-lock.json
    |__ key.perm
    |__ cert.perm
    |__ generate_cert.sh
    |__ install_service.js
    |__ **public/**
             |__ webrtc.js
             |__ index.html
             |__ style.css
```
              
Locally, I can open multiple tabs in Chrome and I see myself  many times duplicated. Which is ok. 
I can also duplicate tabs on remote server and I can see all my duplications in one tab. Which is also ok.

But if I test it on the remote server with my colleague: he sees only himself and I see only myself. Which is absolutelly horrible. And no errors or whatsoever in console. 
I am struggling around this problem for some days already, obviously, a lack of experience doesn't let me solve it by myself.
Could you let me know, what I am doing wrong?

Error on remote server:
`webrtc.js:44 WebSocket connection to 'wss://localhost:8443/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

P.S. I couldn't connect from my mobile also. I saw a topic here already, but I don't find any mobile stun servers.

**Comment by vol-and** [comment]
I've managed to run this thing, but the behaviour is strange:

I create the room by going to root address and I see myself. A remote client from different network connects to my room and also sees only himself. We don't see each other, despite that fact that we are in the same room and the console shows, that a new user was connected.

Accidentally, duplicated my tab during this session and in a new tab I saw my stream together with a remote client stream. In order to see me the remote client  has  to duplicate his chrome tab also. So, 2 tabs by me and 2 tabs by remote. On the first tab I see myself 2 times, but on the second tab I see myself and a remote client. 

Has someone encountered the same behaviour ?

**Comment by shanet** [comment]
Hi @vol-and, I'm catching up on issues in this repo.

> Accidentally, duplicated my tab during this session and in a new tab I saw my stream together with a remote client stream. 

Between this and the prior error of `net::ERR_CONNECTION_REFUSED`, my guess would be that a firewall or something is blocking traffic between the two networks here since it works when you connect two tabs on the same system.
