### ISSUE TITLE
Use `addTrack` instead of depricated `addStream`

### ISSUE THREAD

**Issue by coderfin** [shanet/WebRTC-Example#44]
### First, thanks for creating and maintaining this repo.  I found it very helpful.  🎉 

<br />

#### Issue
On [this line](https://github.com/shanet/WebRTC-Example/blob/dec89dac53e5466871ee5a8bb65d4136cbbf5052/client/webrtc.js#L45) instead of using the now deprecated [addStream](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream) you could use [addTrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack).

```
localStream.getTracks().forEach((track) => peerConnection.addTrack(track, localStream))
```

**Comment by shanet** [comment]
Fixed in a171e04. Thanks for bringing that to my attention.
