### ISSUE TITLE
Got problem with ICE candidate on Chrome on Windows

### ISSUE THREAD

**Issue by ketting00** [shanet/WebRTC-Example#7]
Nice stuff,

I got this error: Uncaught SyntaxError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': The ICE candidate could not be added.

For this line of code: peerConnection.addIceCandidate(new RTCIceCandidate(signal.ice));

And one more question: Do you pipe everything through the websocket. I mean both audio and video data frame at the same time. I use different technique and experienced data clogging or data bottleneck sending video or audio data alone through websocket.

Response will be greatly appreciated. I've a plan to make use of your code with more complicated stuffs. Hope you don't mind about that.

**Comment by shanet** [comment]
Yeah, I need to fix that. Quite busy recently unfortunately. PRs are always welcome though.

The websocket is only for exchanging ICE candidates. After that, everything else is handled by the browser. After all, WebRTC is peer-to-peer so once two clients know how to connect, there's no need for an intermediary server at all.

**Comment by ketting00** [comment]
Wow! That's amazing.

I've never known about that and have been using wrong technology for long time. Thanks for the information.

However, on testing with multiple users the code doesn't work. It only works on one-to-one communication. But that's the nature of WebRTC. My goal is to do something like Facebook's Live feature.

Give me times and I may be able to fix that error. I think.

Thanks for this amazing work and sharing it.

**Comment by shanet** [comment]
It's possible to have multiple users directly connecting to one another. Impractical, but possible.

**Comment by ketting00** [comment]
I got my problem fixed.

It has to do with signal.sdp.type.
There are two types of sdp signal, depending on which side of the peer that sending or receiving a signal. It's too complicated to get it fixed in a simple app though.

**Comment by shanet** [comment]
Fixed in 76cac6ea218c254ce1319693b5e05306d412d8b2.

**Comment by ketting00** [comment]
Thank you for the fix.
