### ISSUE TITLE
"onaddstream" is deprecated

### ISSUE THREAD

**Issue by wdesign22** [shanet/WebRTC-Example#8]
Hey.
Today my browser said me "RTCPeerConnection.onaddstream is deprecated. Use RTCPeerConnection.ontrack".
:)

**Comment by shanet** [comment]
What browser are you using? I assume this is very new since the documentation for `onaddstream` does not note that it is deprecated and the only reference I can find to `ontrack` is noted simply with "blah." (https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection)

**Comment by wdesign22** [comment]
I use firefox.

**Comment by shanet** [comment]
This was added to the API documentation linked above recently: `Old or extension event handlers; they'll be sorted through soon:`

Looks like it's being worked on, but I don't want to change it in this repo until it's a bit more stable. Thanks for bringing this to my attention.

**Comment by shanet** [comment]
Thanks, I just updated it to use `ontrack`.
