### ISSUE TITLE
adapter-latest.js failed

### ISSUE THREAD

**Issue by fatalfeel** [shanet/WebRTC-Example#9]
use firefox 41.0.2
http://webrtc.github.io/adapter/adapter-latest.js
fail line 
 var makeMapStats = (stats, legacyStats) => {
//////////////
npm install webrtc-adapter
after change to adapter.js then works fine...
/////////////
firefox 41.0.2
webrtc.js error in this line 
serverConnection = new WebSocket('wss://' + window.location.hostname + ':8443');
change to chrome then works fine
//////////////

can improve for firefox?

**Comment by shanet** [comment]
It works as intended for me in Firefox 46. I'd recommend upgrading from Firefox 41 as it's quite old at this point.

In general, being that this is an example implementation of WebRTC, I'm not terribly interested in providing backwards compatibility for old browsers. The latest and greatest is more relevant here. Anything specific to a given environment is left as an exercise to the reader.

**Comment by fatalfeel** [comment]
i download the v43 firefox same problem
//////////////////////
and serverConnection = new WebSocket('wss://' + window.location.hostname + ':8443');
still can not work

**Comment by fatalfeel** [comment]
after donwload firefox v46 is ok~~~ fixed
